/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe — siempre devuelve 200 mientras el proceso esté arriba.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe — extiende healthz con check de dependencias críticas.
         *
         *     En F1 es equivalente a healthz; cuando agreguemos checks reales (DB,
         *     LLM client) este endpoint los validará antes de devolver 200.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Templates
         * @description Lista los tipos de template disponibles.
         */
        get: operations["listar_templates_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/mrm/secciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Secciones Mrm
         * @description Catálogo NYL Model Development plano (28 secciones).
         */
        get: operations["listar_secciones_mrm_templates_mrm_secciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/mrm/capitulos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Capitulos Mrm
         * @description Agrupación de secciones en los 9 capítulos NYL.
         */
        get: operations["listar_capitulos_mrm_templates_mrm_capitulos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/prophet/secciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Secciones Prophet
         * @description Catálogo Ficha Prophet.
         */
        get: operations["listar_secciones_prophet_templates_prophet_secciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogos/motivos-omision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Motivos Omision Catalog
         * @description Catálogo de motivos sugeridos para omitir secciones.
         */
        get: operations["motivos_omision_catalog_catalogos_motivos_omision_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogos/ok": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog Health
         * @description Sanity check del catálogo (no se usa en prod).
         */
        get: operations["catalog_health_catalogos_ok_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prophet/detectar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detectar Modelos
         * @description Analiza el Excel del registro y devuelve los modelos detectados.
         *
         *     Útil para presentar al usuario una lista de modelos del registro antes
         *     de elegir cuál importar como Ficha Prophet.
         */
        post: operations["detectar_modelos_prophet_detectar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prophet/importar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importar Registro
         * @description Crea una Ficha Prophet pre-poblada a partir del registro Excel.
         */
        post: operations["importar_registro_prophet_importar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/importar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importar Documento
         * @description Importa un documento .docx/.pdf y devuelve el documento parseado.
         *
         *     El archivo ancla se parsea contra el catálogo NYL Model Development.
         *     Las fuentes adicionales (PDF/XLSX/TXT/DOCX) se procesan para auto-poblar
         *     secciones vacías mediante SugerenciasMultiFuente — requiere LLM.
         */
        post: operations["importar_documento_documentos_importar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Documentos
         * @description Lista los documentos del usuario filtrados por visibilidad.
         */
        get: operations["listar_documentos_documentos_get"];
        put?: never;
        /**
         * Crear Documento
         * @description Crea un documento en blanco con las secciones del template.
         *
         *     - `tipo=model_development` usa el catálogo NYL Model Development.
         *     - `tipo=prophet` usa el catálogo Prophet.
         */
        post: operations["crear_documento_documentos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Documento
         * @description Devuelve un documento completo con todas sus secciones.
         */
        get: operations["obtener_documento_documentos__documento_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar Metadata
         * @description Actualiza la metadata del modelo. Solo se aplican los campos enviados.
         */
        patch: operations["editar_metadata_documentos__documento_id__metadata_patch"];
        trace?: never;
    };
    "/documentos/{documento_id}/archivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archivar */
        post: operations["archivar_documentos__documento_id__archivar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/desarchivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desarchivar */
        post: operations["desarchivar_documentos__documento_id__desarchivar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/papelera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar A Papelera */
        post: operations["enviar_a_papelera_documentos__documento_id__papelera_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/restaurar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restaurar De Papelera */
        post: operations["restaurar_de_papelera_documentos__documento_id__restaurar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/permanente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar Permanente
         * @description Borra el documento físicamente. Requiere rol admin.
         *
         *     El flag `es_admin` se setea en True solo si el bearer token corresponde
         *     al password administrativo (el mismo que el gate). Una vez Cognito esté
         *     real (Fase A.1.c), se leerá del JWT claim.
         */
        delete: operations["eliminar_permanente_documentos__documento_id__permanente_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar Estado
         * @description Mueve el documento entre estados MRM (draft → in_review → approved → published).
         *
         *     Si la transición es inválida según la state machine, devuelve 409 Conflict
         *     con la lista de razones.
         */
        post: operations["cambiar_estado_documentos__documento_id__estado_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/signoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar Signoff
         * @description Registra firma de Reviewer o FAE. Solo válido en estado in_review.
         */
        post: operations["registrar_signoff_documentos__documento_id__signoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/papelera/purgar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purgar Papelera
         * @description Borra documentos que llevan más de `dias` en papelera.
         *
         *     Idempotente. Se puede llamar manualmente o desde un cron.
         */
        post: operations["purgar_papelera_documentos_papelera_purgar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/secciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Secciones
         * @description Lista todas las secciones del documento (vacías y llenas).
         */
        get: operations["listar_secciones_documentos__documento_id__secciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/secciones/{seccion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Seccion
         * @description Devuelve una sección específica del documento.
         */
        get: operations["obtener_seccion_documentos__documento_id__secciones__seccion_id__get"];
        /**
         * Editar Seccion
         * @description Reemplaza el contenido de una sección.
         *
         *     La completitud se recalcula automáticamente:
         *     - vacío → "vacia"
         *     - <200 caracteres → "parcial"
         *     - ≥200 caracteres → "completa"
         *
         *     Esta heurística replica la del reader/editor MRM. Para Prophet, la
         *     completitud se setea a "completa" ya que el contenido es JSON
         *     estructurado (no aplica la regla de longitud).
         */
        put: operations["editar_seccion_documentos__documento_id__secciones__seccion_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/secciones/{seccion_id}/omitir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Omitir Seccion
         * @description Marca una sección como omitida con motivo justificado.
         *
         *     Una sección omitida cuenta como "resuelta" para la state machine —
         *     permite avanzar a in_review sin tener que llenar contenido. El motivo
         *     queda registrado tanto en `seccion.motivo_omision` como en el
         *     audit_trail.
         */
        post: operations["omitir_seccion_documentos__documento_id__secciones__seccion_id__omitir_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/secciones/{seccion_id}/reactivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reactivar Seccion
         * @description Quita la marca de omitida. Vuelve la sección a estado 'vacia'.
         */
        post: operations["reactivar_seccion_documentos__documento_id__secciones__seccion_id__reactivar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/brechas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Brechas
         * @description Ejecuta el GapAnalyzer y devuelve las brechas detectadas.
         *
         *     El cálculo es síncrono y rápido — son reglas estáticas sobre el
         *     documento (no llama al LLM).
         */
        get: operations["listar_brechas_documentos__documento_id__brechas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Auditoria
         * @description Devuelve el audit_trail del documento (más reciente primero).
         */
        get: operations["listar_auditoria_documentos__documento_id__auditoria_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/exportar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exportar Docx
         * @description Genera el .docx con marca SMNYL y lo devuelve como descarga directa.
         *
         *     Headers:
         *     - `Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document`
         *     - `Content-Disposition: attachment; filename="<nombre>.docx"`
         */
        post: operations["exportar_docx_documentos__documento_id__exportar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/exportar/prophet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exportar Ficha Prophet
         * @description Genera la Ficha Prophet DOCX. Requiere `tipo='prophet'`.
         */
        post: operations["exportar_ficha_prophet_documentos__documento_id__exportar_prophet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/polish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Polish Documento
         * @description Ejecuta DocumentPolisher: Claude revisa el documento completo y
         *     reporta inconsistencias entre secciones (no modifica nada).
         *
         *     Requiere LLM configurado (ANTHROPIC_API_KEY). Si no está, devuelve 503.
         */
        post: operations["polish_documento_documentos__documento_id__polish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/entrevista/{seccion_id}/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar Entrevista
         * @description Arranca o reanuda una entrevista sobre la sección.
         *
         *     Si ya había un estado en progreso, lo retoma sin perder mensajes.
         */
        post: operations["iniciar_entrevista_documentos__documento_id__entrevista__seccion_id__iniciar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/entrevista/{seccion_id}/responder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Responder Pregunta
         * @description Procesa el turno del usuario: dispara LLM, persiste estado.
         *
         *     Si el motor marca la sección como cerrada y el Drafter produce un
         *     borrador suficiente, devuelve el `borrador` en el response.
         */
        post: operations["responder_pregunta_documentos__documento_id__entrevista__seccion_id__responder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/entrevista/{seccion_id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Estado
         * @description Devuelve la entrevista en curso sin tocar LLM.
         *
         *     Útil para que el frontend hidrate el chat al reabrir la página.
         */
        get: operations["obtener_estado_documentos__documento_id__entrevista__seccion_id__estado_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/entrevista/{seccion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Descartar Entrevista
         * @description Borra la entrevista en curso para esta sección (no afecta al documento).
         */
        delete: operations["descartar_entrevista_documentos__documento_id__entrevista__seccion_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/apendices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Apendices
         * @description Lista los apéndices del documento.
         */
        get: operations["listar_apendices_documentos__documento_id__apendices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/secciones/{seccion_id}/apendices/tabla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjuntar Tabla
         * @description Sube un Excel/CSV y crea uno o más apéndices (uno por hoja con datos).
         */
        post: operations["adjuntar_tabla_documentos__documento_id__secciones__seccion_id__apendices_tabla_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/secciones/{seccion_id}/apendices/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjuntar Pdf
         * @description Sube un PDF — cada página se embebe como imagen al exportar.
         */
        post: operations["adjuntar_pdf_documentos__documento_id__secciones__seccion_id__apendices_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/secciones/{seccion_id}/apendices/formula": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjuntar Formula
         * @description Adjunta una fórmula LaTeX (se renderea como imagen al exportar).
         */
        post: operations["adjuntar_formula_documentos__documento_id__secciones__seccion_id__apendices_formula_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/apendices/{apendice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Borrar Apendice
         * @description Quita un apéndice del documento (no borra el archivo del storage).
         */
        delete: operations["borrar_apendice_documentos__documento_id__apendices__apendice_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/versiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Versiones
         * @description Devuelve las versiones del documento (numeradas desc).
         */
        get: operations["listar_versiones_documentos__documento_id__versiones_get"];
        put?: never;
        /**
         * Crear Version
         * @description Crea un snapshot inmutable del documento actual.
         *
         *     Si el snapshot es idéntico al de la última versión (mismo hash),
         *     devuelve la versión existente — idempotencia natural.
         */
        post: operations["crear_version_documentos__documento_id__versiones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versiones/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Version
         * @description Metadata de una versión específica.
         */
        get: operations["obtener_version_versiones__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versiones/{version_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Snapshot
         * @description Devuelve el snapshot_json crudo (sin envolver) de la versión.
         *
         *     Útil para diff entre versiones o reconstruir estados previos.
         */
        get: operations["obtener_snapshot_versiones__version_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApendiceDTO */
        ApendiceDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Seccion Origen Id */
            seccion_origen_id: string;
            /** Titulo */
            titulo: string;
            /** Tipo */
            tipo: string;
            /** Nombre Archivo Original */
            nombre_archivo_original: string;
            /**
             * Contenido Md
             * @default
             */
            contenido_md: string;
        };
        /** Body_adjuntar_pdf_documentos__documento_id__secciones__seccion_id__apendices_pdf_post */
        Body_adjuntar_pdf_documentos__documento_id__secciones__seccion_id__apendices_pdf_post: {
            /**
             * Archivo
             * Format: binary
             * @description .pdf
             */
            archivo: string;
            /**
             * Titulo
             * @description Título del apéndice.
             */
            titulo: string;
        };
        /** Body_adjuntar_tabla_documentos__documento_id__secciones__seccion_id__apendices_tabla_post */
        Body_adjuntar_tabla_documentos__documento_id__secciones__seccion_id__apendices_tabla_post: {
            /**
             * Archivo
             * Format: binary
             * @description .xlsx, .xls o .csv
             */
            archivo: string;
            /**
             * Titulo Base
             * @description Título base; multihoja agrega ' — {hoja}'
             */
            titulo_base: string;
        };
        /** Body_detectar_modelos_prophet_detectar_post */
        Body_detectar_modelos_prophet_detectar_post: {
            /**
             * Archivo
             * Format: binary
             * @description Excel del registro Prophet.
             */
            archivo: string;
        };
        /** Body_importar_documento_documentos_importar_post */
        Body_importar_documento_documentos_importar_post: {
            /**
             * Ancla
             * Format: binary
             * @description Archivo .docx o .pdf que da estructura.
             */
            ancla: string;
            /**
             * Fuentes
             * @description Fuentes adicionales para auto-poblar secciones vacías.
             */
            fuentes?: string[];
            /**
             * Actor
             * @default default
             */
            actor: string;
        };
        /** Body_importar_registro_prophet_importar_post */
        Body_importar_registro_prophet_importar_post: {
            /**
             * Archivo
             * Format: binary
             * @description Excel del registro Prophet.
             */
            archivo: string;
            /**
             * Fila Idx
             * @description Fila base-0 en Descripcion_General del modelo.
             */
            fila_idx: number;
            /**
             * Nombre Modelo
             * @description Nombre humano del modelo (ej. 'VNB').
             */
            nombre_modelo: string;
            /**
             * Actor
             * @default default
             */
            actor: string;
        };
        /**
         * BrechaDTO
         * @description Vista de una brecha detectada por el GapAnalyzer.
         */
        BrechaDTO: {
            /** Seccion Id */
            seccion_id: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "seccion_faltante" | "seccion_vacia" | "seccion_incompleta" | "metadata_faltante" | "supuesto_no_documentado" | "limitacion_no_documentada";
            /**
             * Severidad
             * @enum {string}
             */
            severidad: "alta" | "media" | "baja";
            /** Mensaje */
            mensaje: string;
            /**
             * Sugerencia
             * @default
             */
            sugerencia: string;
        };
        /**
         * CambiarEstadoRequest
         * @description Payload para transición del documento entre estados MRM.
         *
         *     Las transiciones válidas se definen en src.core.rules.DocumentStateMachine.
         *     Si la transición es inválida, devuelve 409 Conflict con las razones.
         */
        CambiarEstadoRequest: {
            /**
             * Destino
             * @enum {string}
             */
            destino: "draft" | "in_review" | "approved" | "published" | "retired";
            /**
             * Actor
             * @default default
             */
            actor: string;
        };
        /**
         * CrearDocumentoRequest
         * @description Payload para POST /documentos.
         *
         *     Crea un documento en blanco con las secciones del template oficial.
         *     Si `tipo='prophet'`, usa el catálogo Prophet.
         */
        CrearDocumentoRequest: {
            /**
             * Tipo
             * @default model_development
             * @enum {string}
             */
            tipo: "model_development" | "prophet";
            /**
             * Nombre Modelo
             * @description Nombre opcional inicial. Editable después en metadata.
             * @default
             */
            nombre_modelo: string;
            /**
             * Actor
             * @description user_id del creador.
             * @default default
             */
            actor: string;
        };
        /**
         * CrearVersionRequest
         * @description Payload para POST /documentos/{id}/versiones.
         */
        CrearVersionRequest: {
            /**
             * Comentario
             * @default
             */
            comentario: string;
            /**
             * Actor
             * @default default
             */
            actor: string;
        };
        /**
         * DocumentoDTO
         * @description Vista completa de un Documento — incluye secciones.
         */
        DocumentoDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "model_development" | "prophet";
            /**
             * Estado
             * @enum {string}
             */
            estado: "draft" | "in_review" | "approved" | "published" | "retired";
            /**
             * Visibilidad
             * @enum {string}
             */
            visibilidad: "activo" | "archivado" | "papelera";
            metadata_modelo: components["schemas"]["MetadataModeloDTO"];
            /** Secciones */
            secciones: components["schemas"]["SeccionDTO"][];
            /** Porcentaje Completitud */
            porcentaje_completitud: number;
            /** Porcentaje Resuelto */
            porcentaje_resuelto: number;
            /** Cobertura Catalogo */
            cobertura_catalogo: number;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            /** Archivo Origen */
            archivo_origen?: string | null;
            /** Archivado */
            archivado: boolean;
            /** Archivado En */
            archivado_en?: string | null;
            /** En Papelera */
            en_papelera: boolean;
            /** N Eventos Audit */
            n_eventos_audit: number;
        };
        /**
         * DocumentoListItem
         * @description Vista resumida de un Documento para listas (home, dashboard).
         */
        DocumentoListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "model_development" | "prophet";
            /**
             * Estado
             * @enum {string}
             */
            estado: "draft" | "in_review" | "approved" | "published" | "retired";
            /**
             * Visibilidad
             * @enum {string}
             */
            visibilidad: "activo" | "archivado" | "papelera";
            /**
             * Nombre Modelo
             * @description metadata_modelo.nombre_modelo o ''.
             */
            nombre_modelo: string;
            /** Porcentaje Completitud */
            porcentaje_completitud: number;
            /** Porcentaje Resuelto */
            porcentaje_resuelto: number;
            /** N Secciones */
            n_secciones: number;
            /** N Secciones Obligatorias */
            n_secciones_obligatorias: number;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            /** Archivado */
            archivado: boolean;
            /** En Papelera */
            en_papelera: boolean;
        };
        /**
         * EditarMetadataRequest
         * @description Payload para PATCH /documentos/{id}/metadata.
         *
         *     Todos los campos son opcionales — solo se actualizan los enviados.
         */
        EditarMetadataRequest: {
            /** Nombre Modelo */
            nombre_modelo?: string | null;
            /** Model Id */
            model_id?: string | null;
            /** Model Class */
            model_class?: string | null;
            /** Profit Center */
            profit_center?: string | null;
            /** Fae */
            fae?: string | null;
            /** Model Owner */
            model_owner?: string | null;
            /** Model Developers */
            model_developers?: string[] | null;
            /** Model Users */
            model_users?: string[] | null;
            /** Current Version */
            current_version?: string | null;
            /** Implementation Platform */
            implementation_platform?: string | null;
            /** Financial Impact */
            financial_impact?: string | null;
            /** Model Status */
            model_status?: string | null;
            /** Target Production Date */
            target_production_date?: string | null;
            /** Inherent Risk Tier */
            inherent_risk_tier?: ("low" | "medium_minus" | "medium" | "high" | "very_high" | "very_high_plus" | "critical") | null;
            /** Intended Use */
            intended_use?: string | null;
            /** Use Restrictions */
            use_restrictions?: string | null;
            /** Nomenclatura */
            nomenclatura?: string | null;
        };
        /**
         * EditarSeccionRequest
         * @description Payload para PUT /documentos/{id}/secciones/{sid}.
         *
         *     El contenido es markdown libre (MRM) o JSON estructurado (Prophet).
         *     La completitud se recalcula automáticamente según la longitud del
         *     contenido — el caller no necesita enviarla.
         */
        EditarSeccionRequest: {
            /**
             * Contenido
             * @description Contenido nuevo (markdown o JSON).
             */
            contenido: string;
            /**
             * Actor
             * @default default
             */
            actor: string;
        };
        /**
         * EventoDTO
         * @description Vista de un evento del audit_trail.
         */
        EventoDTO: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Actor */
            actor: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "documento_creado" | "documento_importado" | "seccion_editada" | "seccion_completada" | "seccion_omitida" | "transicion_estado" | "metadata_actualizada" | "exportado" | "signoff_reviewer" | "signoff_fae" | "archivado" | "desarchivado" | "enviado_a_papelera" | "restaurado_de_papelera" | "eliminado_permanente" | "purgado_automatico" | "version_creada" | "version_restaurada";
            /** Descripcion */
            descripcion: string;
            /** Seccion Id */
            seccion_id?: string | null;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: string;
            };
        };
        /**
         * ExportarRequest
         * @description Opciones del export DOCX.
         *
         *     Mapea 1:1 al `ExportarDocumento.ejecutar(...)`. Default: bilingue
         *     (sin cambiar el idioma del contenido) + sin polish + sin versión.
         */
        ExportarRequest: {
            /**
             * Idioma Objetivo
             * @default bilingue
             * @enum {string}
             */
            idioma_objetivo: "es" | "en" | "es_normalize" | "en_normalize" | "bilingue";
            /**
             * Polish
             * @description Si True, ejecuta DocumentPolisher antes del export.
             * @default false
             */
            polish: boolean;
            /**
             * Crear Version
             * @description Si True, crea una versión inmutable (snapshot) al exportar.
             * @default false
             */
            crear_version: boolean;
            /**
             * Comentario Version
             * @description Comentario para la versión.
             * @default
             */
            comentario_version: string;
            /**
             * Actor
             * @default default
             */
            actor: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Api
             * @default documente
             */
            api: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /**
         * IniciarEntrevistaResponse
         * @description Respuesta del POST /entrevista/iniciar.
         */
        IniciarEntrevistaResponse: {
            turno: components["schemas"]["TurnoEntrevistaDTO"];
            /** Seccion Id */
            seccion_id: string;
            /**
             * Mensajes
             * @description Historial completo (puede traer mensajes previos si la entrevista se reanudó).
             */
            mensajes?: components["schemas"]["MensajeDTO"][];
        };
        /**
         * MensajeDTO
         * @description Un mensaje del chat de entrevista.
         */
        MensajeDTO: {
            /**
             * Rol
             * @enum {string}
             */
            rol: "user" | "assistant" | "system_note";
            /** Contenido */
            contenido: string;
        };
        /**
         * MetadataModeloDTO
         * @description Metadata estructurada del modelo (tabla de atributos, sección 1.1).
         */
        MetadataModeloDTO: {
            /**
             * Nombre Modelo
             * @default
             */
            nombre_modelo: string;
            /**
             * Model Id
             * @default
             */
            model_id: string;
            /**
             * Model Class
             * @default
             */
            model_class: string;
            /**
             * Profit Center
             * @default
             */
            profit_center: string;
            /**
             * Fae
             * @default
             */
            fae: string;
            /**
             * Model Owner
             * @default
             */
            model_owner: string;
            /** Model Developers */
            model_developers?: string[];
            /** Model Users */
            model_users?: string[];
            /**
             * Current Version
             * @default
             */
            current_version: string;
            /**
             * Implementation Platform
             * @default
             */
            implementation_platform: string;
            /**
             * Financial Impact
             * @default
             */
            financial_impact: string;
            /**
             * Model Status
             * @default
             */
            model_status: string;
            /**
             * Target Production Date
             * @default
             */
            target_production_date: string;
            /** Inherent Risk Tier */
            inherent_risk_tier?: ("low" | "medium_minus" | "medium" | "high" | "very_high" | "very_high_plus" | "critical") | null;
            /**
             * Intended Use
             * @default
             */
            intended_use: string;
            /**
             * Use Restrictions
             * @default
             */
            use_restrictions: string;
            /**
             * Nomenclatura
             * @default
             */
            nomenclatura: string;
        };
        /** ModeloProphetInfo */
        ModeloProphetInfo: {
            /** Fila Idx */
            fila_idx: number;
            /** Nombre */
            nombre: string;
            /** Encargado */
            encargado: string;
            /**
             * Area
             * @default
             */
            area: string;
            /**
             * Proceso
             * @default
             */
            proceso: string;
        };
        /**
         * OkResponse
         * @description Respuesta genérica de éxito sin payload.
         */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Mensaje
             * @default
             */
            mensaje: string;
        };
        /**
         * OmitirSeccionRequest
         * @description Payload para POST /documentos/{id}/secciones/{sid}/omitir.
         */
        OmitirSeccionRequest: {
            /**
             * Motivo
             * @description Razón documentada — del catálogo MOTIVOS_OMISION o texto libre. No puede estar vacío (decisión auditable MRM §3.5).
             */
            motivo: string;
            /**
             * Actor
             * @default default
             */
            actor: string;
        };
        /**
         * RegistrarSignoffRequest
         * @description Payload para registrar firma de Reviewer o FAE.
         *
         *     El actor (user_id) firma como `rol`. El use case verifica independencia
         *     respecto a Owner y Developer del modelo (MRM §3.5).
         */
        RegistrarSignoffRequest: {
            /**
             * Rol
             * @enum {string}
             */
            rol: "reviewer" | "fae";
            /**
             * Actor
             * @description user_id del firmante.
             * @default default
             */
            actor: string;
        };
        /**
         * ResponderPreguntaRequest
         * @description Payload del POST /entrevista/responder.
         */
        ResponderPreguntaRequest: {
            /**
             * Respuesta
             * @description Texto libre del usuario.
             */
            respuesta: string;
            /**
             * Actor
             * @default default
             */
            actor: string;
        };
        /**
         * SeccionDTO
         * @description Vista completa de una sección.
         */
        SeccionDTO: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Numero */
            numero: string;
            /** Obligatoria */
            obligatoria: boolean;
            /** Contenido */
            contenido?: string | null;
            /**
             * Completitud
             * @default vacia
             * @enum {string}
             */
            completitud: "vacia" | "parcial" | "completa" | "omitida";
            /**
             * Intencion
             * @default
             */
            intencion: string;
            /** Preguntas Guia */
            preguntas_guia?: string[];
            /** Motivo Omision */
            motivo_omision?: string | null;
            /** Tiene Contenido */
            tiene_contenido: boolean;
        };
        /** SugerenciaPolish */
        SugerenciaPolish: {
            /** Seccion Id */
            seccion_id: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "inconsistencia" | "contradiccion" | "redaccion" | "referencia_rota";
            /**
             * Severidad
             * @enum {string}
             */
            severidad: "alta" | "media" | "baja";
            /** Descripcion */
            descripcion: string;
            /** Secciones Afectadas */
            secciones_afectadas?: string[];
            /** Texto Sugerido */
            texto_sugerido?: string | null;
        };
        /**
         * TurnoEntrevistaDTO
         * @description Un turno de entrevista: pregunta del asistente + estado actual.
         */
        TurnoEntrevistaDTO: {
            /**
             * Respuesta Asistente
             * @description Pregunta o cierre del asistente.
             */
            respuesta_asistente: string;
            /**
             * Seccion Cerrada
             * @description True si la sección quedó cerrada (con borrador suficiente) este turno.
             */
            seccion_cerrada: boolean;
            /**
             * Borrador
             * @description Si la sección cerró, borrador final que se guardó.
             */
            borrador?: string | null;
            /**
             * N Mensajes
             * @description Total acumulado de mensajes en la sesión.
             */
            n_mensajes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionDTO
         * @description Vista de un snapshot inmutable del documento.
         *
         *     No incluye `snapshot_json` para mantener la lista liviana — el
         *     contenido se descarga vía endpoint separado.
         */
        VersionDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Documento Id
             * Format: uuid
             */
            documento_id: string;
            /** Numero */
            numero: number;
            /** Comentario */
            comentario: string;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /** Hash Contenido */
            hash_contenido: string;
        };
        /** _AccionVisibilidadRequest */
        _AccionVisibilidadRequest: {
            /**
             * Razon
             * @default
             */
            razon: string;
            /**
             * Actor
             * @default default
             */
            actor: string;
        };
        /** _CapituloDTO */
        _CapituloDTO: {
            /** Numero */
            numero: string;
            /** Nombre */
            nombre: string;
            /** Secciones */
            secciones: components["schemas"]["_SeccionCatalogoDTO"][];
        };
        /** _DeteccionResponse */
        _DeteccionResponse: {
            /** Modelos */
            modelos: components["schemas"]["ModeloProphetInfo"][];
            /**
             * Advertencias
             * @default []
             */
            advertencias: string[];
        };
        /** _FormulaRequest */
        _FormulaRequest: {
            /** Latex Source */
            latex_source: string;
            /** Titulo */
            titulo: string;
        };
        /** _PolishResultadoDTO */
        _PolishResultadoDTO: {
            /** Sugerencias */
            sugerencias: components["schemas"]["SugerenciaPolish"][];
            /** N Sugerencias */
            n_sugerencias: number;
        };
        /** _SeccionCatalogoDTO */
        _SeccionCatalogoDTO: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Numero */
            numero: string;
            /** Obligatoria */
            obligatoria: boolean;
            /**
             * Intencion
             * @default
             */
            intencion: string;
            /**
             * Preguntas Guia
             * @default []
             */
            preguntas_guia: string[];
        };
        /** _TemplateInfo */
        _TemplateInfo: {
            /** Tipo */
            tipo: string;
            /** Nombre */
            nombre: string;
            /** N Secciones */
            n_secciones: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listar_templates_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_TemplateInfo"][];
                };
            };
        };
    };
    listar_secciones_mrm_templates_mrm_secciones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_SeccionCatalogoDTO"][];
                };
            };
        };
    };
    listar_capitulos_mrm_templates_mrm_capitulos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_CapituloDTO"][];
                };
            };
        };
    };
    listar_secciones_prophet_templates_prophet_secciones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_SeccionCatalogoDTO"][];
                };
            };
        };
    };
    motivos_omision_catalog_catalogos_motivos_omision_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    catalog_health_catalogos_ok_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    detectar_modelos_prophet_detectar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_detectar_modelos_prophet_detectar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_DeteccionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    importar_registro_prophet_importar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_importar_registro_prophet_importar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    importar_documento_documentos_importar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_importar_documento_documentos_importar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_documentos_documentos_get: {
        parameters: {
            query?: {
                /** @description Filtro de visibilidad: activos (default), archivados, papelera, o todos. */
                visibilidad?: "activos" | "archivados" | "papelera" | "todos";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_documento_documentos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearDocumentoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_documento_documentos__documento_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_metadata_documentos__documento_id__metadata_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarMetadataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archivar_documentos__documento_id__archivar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_AccionVisibilidadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desarchivar_documentos__documento_id__desarchivar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enviar_a_papelera_documentos__documento_id__papelera_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_AccionVisibilidadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restaurar_de_papelera_documentos__documento_id__restaurar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_permanente_documentos__documento_id__permanente_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_estado_documentos__documento_id__estado_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarEstadoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_signoff_documentos__documento_id__signoff_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarSignoffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purgar_papelera_documentos_papelera_purgar_post: {
        parameters: {
            query?: {
                /** @description Umbral en días para purga. */
                dias?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_secciones_documentos__documento_id__secciones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeccionDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_seccion_documentos__documento_id__secciones__seccion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeccionDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_seccion_documentos__documento_id__secciones__seccion_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarSeccionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeccionDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    omitir_seccion_documentos__documento_id__secciones__seccion_id__omitir_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OmitirSeccionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeccionDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivar_seccion_documentos__documento_id__secciones__seccion_id__reactivar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeccionDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_brechas_documentos__documento_id__brechas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrechaDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_auditoria_documentos__documento_id__auditoria_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Offset para paginación simple. */
                desde?: number;
            };
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportar_docx_documentos__documento_id__exportar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportar_ficha_prophet_documentos__documento_id__exportar_prophet_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    polish_documento_documentos__documento_id__polish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_PolishResultadoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iniciar_entrevista_documentos__documento_id__entrevista__seccion_id__iniciar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IniciarEntrevistaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    responder_pregunta_documentos__documento_id__entrevista__seccion_id__responder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponderPreguntaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoEntrevistaDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_estado_documentos__documento_id__entrevista__seccion_id__estado_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IniciarEntrevistaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    descartar_entrevista_documentos__documento_id__entrevista__seccion_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_apendices_documentos__documento_id__apendices_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApendiceDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjuntar_tabla_documentos__documento_id__secciones__seccion_id__apendices_tabla_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_adjuntar_tabla_documentos__documento_id__secciones__seccion_id__apendices_tabla_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApendiceDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjuntar_pdf_documentos__documento_id__secciones__seccion_id__apendices_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_adjuntar_pdf_documentos__documento_id__secciones__seccion_id__apendices_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApendiceDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjuntar_formula_documentos__documento_id__secciones__seccion_id__apendices_formula_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                seccion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_FormulaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApendiceDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    borrar_apendice_documentos__documento_id__apendices__apendice_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
                apendice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_versiones_documentos__documento_id__versiones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_version_documentos__documento_id__versiones_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_version_versiones__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_snapshot_versiones__version_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
